| [03_data_science/01_Numpy数组.ipynb](https://github.com/shibing624/python-tutorial/blob/master/03_data_science/01_Numpy数组.ipynb)  | Numpy array数组  |[Open In Colab](https://colab.research.google.com/github/shibing624/python-tutorial/blob/master/03_data_science/01_Numpy数组.ipynb) |

# Numpy数组


## 数组：array


很多其他科学计算的第三方库都是以Numpy为基础建立的。

Numpy的一个重要特性是它的数组计算。




使用前一定要先导入 Numpy 包，导入的方法有以下几种：
```
import numpy
import numpy as np
from numpy import *
from numpy import array, sin
```

导入numpy，最常用为这种:

In [1]:
import numpy as np

假如我们想将列表中的每个元素增加1，但列表不支持这样的操作（报错）：

In [2]:
a = [1, 2]

# a + 1 # 报错

使用numpy.array：

In [3]:
a = np.array(a)
a  # [1 2]

array([1, 2])

In [4]:
b = a + 1
b  # array([2,3])

array([2, 3])

与另一个 array 相加，得到对应元素相加的结果：

In [5]:
c = a + b
print(c)  # array([3,5])

# 对应元素相乘：
print(a * b)  # [2 6]

# 对应元素乘方：
print(a ** b)  # [1 8]

[3 5]
[2 6]
[1 8]


### 提取数组中的元素

In [6]:
# 提取第一个
a = np.array([1, 2, 3, 4])
print(a[0])  # 1

# 提取前两个元素：
print(a[:2])  # [1 2]

# 最后两个元素
print(a[-2:])  # [3 4]

# 相加：
print(a[:2] + a[-2:])  # [4 6]

1
[1 2]
[3 4]
[4 6]


### 修改数组形状

查看array的形状：

In [7]:
b = a.shape
b  # (4,)

(4,)

In [8]:
# 修改 array 的形状：
a.shape = 2, 2
a
# [[1 2]
# [3 4]]

array([[1, 2],
       [3, 4]])

In [9]:
# 多维数组
# a 现在变成了一个二维的数组，可以进行加法：
a + a
# [[2 4]
#  [6 8]]

array([[2, 4],
       [6, 8]])

In [10]:
# 乘法仍然是对应元素的乘积，并不是按照矩阵乘法来计算：
a * a
# [[ 1  4]
# [ 9 16]]

array([[ 1,  4],
       [ 9, 16]])

本节完。